-- See https://github.com/rcarriga/nvim-dap-ui/blob/b80227ea56a48177786904f6322abc8b2dc0bc36/lua/dapui/config/highlights.lua
local Set = require("gruvsquirrel.util.set").Set

return Set {
  'DapUIBreakpointsCurrentLine',
  'DapUIBreakpointsDisabledLine',
  'DapUIBreakpointsInfo',
  'DapUIBreakpointsLine',
  'DapUIBreakpointsPath',
  'DapUICurrentFrameName',
  'DapUIDecoration',
  'DapUIFloatBorder',
  'DapUIFloatNormal',
  'DapUIFrameName',
  'DapUILineNumber',
  'DapUIModifiedValue',
  'DapUIPlayPause',
  'DapUIPlayPauseNC',
  'DapUIRestart',
  'DapUIRestartNC',
  'DapUIScope',
  'DapUISource',
  'DapUIStepBack',
  'DapUIStepBackNC',
  'DapUIStepInto',
  'DapUIStepIntoNC',
  'DapUIStepOut',
  'DapUIStepOutNC',
  'DapUIStepOver',
  'DapUIStepOverNC',
  'DapUIStop',
  'DapUIStopNC',
  'DapUIStoppedThread',
  'DapUIThread',
  'DapUIType',
  'DapUIUnavailable',
  'DapUIUnavailableNC',
  'DapUIValue',
  'DapUIVariable',
  'DapUIWatchesEmpty',
  'DapUIWatchesError',
  'DapUIWatchesValue',
}
