-- See https://github.com/neovim/neovim/blob/master/runtime/syntax/netrw.vim
local Set = require("gruvsquirrel.util.set").Set

return Set {
  'netrwClassify',
  'netrwCmdSep',
  'netrwComment',
  'netrwDir',
  'netrwHelpCmd',
  'netrwQHTopic',
  'netrwHidePat',
  'netrwHideSep',
  'netrwList',
  'netrwVersion',
  'netrwSymLink',
  'netrwExe',
  'netrwDateSep',
  'netrwTreeBar',
  'netrwTimeSep',
  'netrwComma',
  'netrwHide',
  'netrwMarkFile',
  'netrwLink',
  'netrwCoreDump',
  'netrwData',
  'netrwHdr',
  'netrwLex',
  'netrwLib',
  'netrwMakefile',
  'netrwYacc',
  'netrwPix',
  'netrwBak',
  'netrwCompress',
  'netrwSpecFile',
  'netrwObj',
  'netrwTags',
  'netrwTilde',
  'netrwTmp',
}
