local with_meta = require("gruvsquirrel.util.tbl").with_meta

--- Telescope Highlight Groups
---@class GruvsquirrelTelescopeGroup
local M = {
  TelescopeTitle = 'TelescopeTitle',
  TelescopeBorder = 'TelescopeBorder',
  TelescopeNormal = 'TelescopeNormal',
  TelescopeMatching = 'TelescopeMatching',
  TelescopeMultiIcon = 'TelescopeMultiIcon',
  TelescopeSelection = 'TelescopeSelection',
  TelescopePreviewDate = 'TelescopePreviewDate',
  TelescopePreviewLine = 'TelescopePreviewLine',
  TelescopePreviewLink = 'TelescopePreviewLink',
  TelescopePreviewPipe = 'TelescopePreviewPipe',
  TelescopePreviewRead = 'TelescopePreviewRead',
  TelescopePreviewSize = 'TelescopePreviewSize',
  TelescopePreviewUser = 'TelescopePreviewUser',
  TelescopePromptTitle = 'TelescopePromptTitle',
  TelescopePreviewBlock = 'TelescopePreviewBlock',
  TelescopePreviewGroup = 'TelescopePreviewGroup',
  TelescopePreviewMatch = 'TelescopePreviewMatch',
  TelescopePreviewTitle = 'TelescopePreviewTitle',
  TelescopePreviewWrite = 'TelescopePreviewWrite',
  TelescopePromptBorder = 'TelescopePromptBorder',
  TelescopePromptNormal = 'TelescopePromptNormal',
  TelescopePromptPrefix = 'TelescopePromptPrefix',
  TelescopeResultsClass = 'TelescopeResultsClass',
  TelescopeResultsField = 'TelescopeResultsField',
  TelescopeResultsTitle = 'TelescopeResultsTitle',
  TelescopePreviewBorder = 'TelescopePreviewBorder',
  TelescopePreviewHyphen = 'TelescopePreviewHyphen',
  TelescopePreviewNormal = 'TelescopePreviewNormal',
  TelescopePreviewSocket = 'TelescopePreviewSocket',
  TelescopePreviewSticky = 'TelescopePreviewSticky',
  TelescopePromptCounter = 'TelescopePromptCounter',
  TelescopeResultsBorder = 'TelescopeResultsBorder',
  TelescopeResultsLineNr = 'TelescopeResultsLineNr',
  TelescopeResultsMethod = 'TelescopeResultsMethod',
  TelescopeResultsNormal = 'TelescopeResultsNormal',
  TelescopeResultsNumber = 'TelescopeResultsNumber',
  TelescopeResultsStruct = 'TelescopeResultsStruct',
  TelescopeMultiSelection = 'TelescopeMultiSelection',
  TelescopePreviewCharDev = 'TelescopePreviewCharDev',
  TelescopePreviewExecute = 'TelescopePreviewExecute',
  TelescopePreviewMessage = 'TelescopePreviewMessage',
  TelescopeResultsComment = 'TelescopeResultsComment',
  TelescopeResultsDiffAdd = 'TelescopeResultsDiffAdd',
  TelescopeSelectionCaret = 'TelescopeSelectionCaret',
  TelescopeResultsConstant = 'TelescopeResultsConstant',
  TelescopeResultsFunction = 'TelescopeResultsFunction',
  TelescopeResultsOperator = 'TelescopeResultsOperator',
  TelescopeResultsVariable = 'TelescopeResultsVariable',
  TelescopePreviewDirectory = 'TelescopePreviewDirectory',
  TelescopeResultsDiffChange = 'TelescopeResultsDiffChange',
  TelescopeResultsDiffDelete = 'TelescopeResultsDiffDelete',
  TelescopeResultsIdentifier = 'TelescopeResultsIdentifier',
  TelescopeResultsDiffUntracked = 'TelescopeResultsDiffUntracked',
  TelescopeResultsSpecialComment = 'TelescopeResultsSpecialComment',
  TelescopePreviewMessageFillchar = 'TelescopePreviewMessageFillchar',
}

---@type GruvsquirrelTelescopeGroup
M = with_meta(M)

return M
