-- See https://github.com/nvim-treesitter/nvim-treesitter/commit/42ab95d5e11f247c6f0c8f5181b02e816caa4a4f#commitcomment-87014462
-- See https://github.com/neovim/neovim/blob/9220755302317e8030c5bbf334357c0d64df9fa4/src/nvim/highlight_group.c
local with_meta = require('gruvsquirrel.util.tbl').with_meta

--- Treesitter Highlight Groups
---@class GruvsquirrelTreesitterGroup
local M = {
  ['@annotation'] = '@annotation',
  ['@attribute'] = '@attribute',
  ['@boolean'] = '@boolean',
  ['@character'] = '@character',
  ['@character.special'] = '@character.special',
  ['@class'] = '@class',
  ['@comment'] = '@comment',
  ['@conditional'] = '@conditional',
  ['@constant'] = '@constant',
  ['@constant.builtin'] = '@constant.builtin',
  ['@constant.macro'] = '@constant.macro',
  ['@constructor'] = '@constructor',
  ['@debug'] = '@debug',
  ['@decorator'] = '@decorator',
  ['@define'] = '@define',
  ['@enum'] = '@enum',
  ['@enumMember'] = '@enumMember',
  ['@event'] = '@event',
  ['@exception'] = '@exception',
  ['@field'] = '@field',
  ['@float'] = '@float',
  ['@function'] = '@function',
  ['@function.builtin'] = '@function.builtin',
  ['@function.call'] = '@function.call',
  ['@function.macro'] = '@function.macro',
  ['@include'] = '@include',
  ['@interface'] = '@interface',
  ['@keyword'] = '@keyword',
  ['@keyword.function'] = '@keyword.function',
  ['@keyword.operator'] = '@keyword.operator',
  ['@keyword.return'] = '@keyword.return',
  ['@label'] = '@label',
  ['@macro'] = '@macro',
  ['@method'] = '@method',
  ['@method.call'] = '@method.call',
  ['@modifier'] = '@modifier',
  ['@namespace'] = '@namespace',
  ['@none'] = '@none',
  ['@number'] = '@number',
  ['@operator'] = '@operator',
  ['@parameter'] = '@parameter',
  ['@preproc'] = '@preproc',
  ['@property'] = '@property',
  ['@punctuation'] = '@punctuation',
  ['@punctuation.bracket'] = '@punctuation.bracket',
  ['@punctuation.delimiter'] = '@punctuation.delimiter',
  ['@punctuation.special'] = '@punctuation.special',
  ['@regexp'] = '@regexp',
  ['@repeat'] = '@repeat',
  ['@storageclass'] = '@storageclass',
  ['@string'] = '@string',
  ['@string.escape'] = '@string.escape',
  ['@string.regex'] = '@string.regex',
  ['@string.special'] = '@string.special',
  ['@struct'] = '@struct',
  ['@symbol'] = '@symbol',
  ['@tag'] = '@tag',
  ['@tag.attribute'] = '@tag.attribute',
  ['@tag.delimiter'] = '@tag.delimiter',
  ['@text'] = '@text',
  ['@text.danger'] = '@text.danger',
  ['@text.diff.add'] = '@text.diff.add',
  ['@text.diff.delete'] = '@text.diff.delete',
  ['@text.emphasis'] = '@text.emphasis',
  ['@text.environment'] = '@text.environment',
  ['@text.environment.name'] = '@text.environment.name',
  ['@text.literal'] = '@text.literal',
  ['@text.math'] = '@text.math',
  ['@text.note'] = '@text.note',
  ['@text.attribute'] = '@text.attribute',
  ['@text.reference'] = '@text.reference',
  ['@text.strike'] = '@text.strike',
  ['@text.strong'] = '@text.strong',
  ['@text.title'] = '@text.title',
  ['@text.todo'] = '@text.todo',
  ['@text.todo.checked'] = '@text.todo.checked',
  ['@text.todo.unchecked'] = '@text.todo.unchecked',
  ['@text.underline'] = '@text.underline',
  ['@text.uri'] = '@text.uri',
  ['@text.warning'] = '@text.warning',
  ['@type'] = '@type',
  ['@type.builtin'] = '@type.builtin',
  ['@type.definition'] = '@type.definition',
  ['@type.qualifier'] = '@type.qualifier',
  ['@typeParameter'] = '@typeParameter',
  ['@variable'] = '@variable',
  ['@variable.builtin'] = '@variable.builtin',
}

---@type GruvsquirrelTreesitterGroup
M = with_meta(M)

return M
