local c = require("gruvsquirrel.colors.gruvsquirrel.palette") -- colors
local g = require("gruvsquirrel.highlight-groups.standard") -- groups
local mapper = require("gruvsquirrel.util.mapper")

local attributes = mapper.highlight_group_mapper {
  { { g.ColorColumn, }, { bg = c.scrat_0 } },
  { { g.LineNr, g.LineNrAbove, g.LineNrBelow }, { fg = c.rocky_3, bg = c.scrat_0 } },
  { { g.CursorLine, }, { bg = c.scrat_1, ctermfg = 'white', } }, -- ctermfg is a hack, see https://github.com/neovim/neovim/issues/9800
  { { g.CursorColumn }, { bg = c.scrat_5 } },
  { { g.Visual, g.VisualNOS }, { bg = c.scrat_3, } },
  { { g.Statement, g.Conceal, g.Identifier, g.Field, g.Property, }, { fg = c.chitter_0 } },
  { { g.CurSearch, g.IncSearch, }, { fg = c.scrat_0, bg = c.sandy_0, } },
  { { g.Cursor, g.lCursor, g.TermCursor }, { reverse = true } },
  { { g.DiffAdd, g.DiffChange, }, { bg = c.doreen_1 } },
  { { g.DiffDelete, }, { fg = c.scrat_0, bg = c.surly_4, } },
  { { g.DiffText }, { fg = c.scrat_5, bg = c.doreen_2, } },
  { { g.NonText, g.Whitespace }, { fg = c.rocky_1, } },
  { { g.EndOfBuffer }, { fg = c.rocky_1, } },
  { { g.TermCursorNC, }, {} },
  { { g.ErrorMsg, }, { fg = c.scrat_0, bg = c.bucky_0, bold = true } },
  { { g.Folded }, { fg = c.rocky_0, bg = c.scrat_0, italic = true } },
  { { g.FoldColumn, g.CursorLineFold }, { fg = c.rocky_0, bg = c.scrat_0 } },
  { { g.Substitute, g.Search }, { fg = c.scrat_0, bg = c.doreen_7, } },
  { { g.CursorLineNr }, { fg = c.sandy_0, bg = c.scrat_1 } },
  { { g.MatchParen }, { reverse = true, bold = true } },
  { { g.ModeMsg, g.MoreMsg, g.Question }, { fg = c.sandy_0, bold = true } },
  { { g.MsgArea }, { fg = c.sally_0, bg = c.scrat_5 } },
  { { g.MsgSeparator }, { fg = c.scrat_5, bg = c.scrat_6, } },
  { { g.Normal }, { fg = c.sally_0, bg = c.scrat_0, } },
  { { g.NormalFloat, g.Pmenu, }, { fg = c.sally_0, bg = c.scrat_6, } },
  { { g.NormalNC }, { fg = c.rocky_4, bg = c.scrat_0 } },
  { { g.PmenuSel, g.QuickFixLine, g.WildMenu, }, { bg = c.chitter_3, } }, -- might need to clear fg
  { { g.PmenuSbar, g.TabLineFill }, { bg = c.scrat_6, } },
  { { g.PmenuThumb }, { bg = c.scrat_3, } },
  { { g.SignColumn, g.CursorLineSign, }, { bg = c.scrat_5 } },
  { { g.SpecialKey }, { fg = c.sandy_0, bg = c.scrat_6, bold = true, } },
  { { g.SpellBad }, { sp = c.bucky_0, undercurl = true, } },
  { { g.SpellCap }, { sp = c.skippy_0, undercurl = true, } },
  { { g.SpellRare }, { sp = c.surly_3, undercurl = true, } },
  { { g.StatusLine, g.TabLineSel, g.winbar }, { fg = c.sally_0, bg = c.scrat_6, bold = true } },
  { { g.StatusLineNC, g.tabline, g.winbarnc }, { fg = c.rocky_0, bg = c.scrat_5 } },
  { { g.Title, g.Function, }, { fg = c.doreen_0 } },
  { { g.WarningMsg, }, { fg = c.bucky_0, bold = true } },
  { { g.WinSeparator }, { fg = c.scrat_6, bg = c.scrat_0 } },
  { { g.Operator }, { fg = c.hammy_0, italic = true } },
  { { g.Comment }, { fg = c.rocky_0, italic = true } },
  { { g.PreProc, g.Define, g.Macro, g.Include, g.Structure, }, { fg = c.skippy_0, } },
  { { g.Delimiter, g.Debug, g.StorageClass, g.Tag, g.Special, g.SpecialChar, }, { fg = c.hammy_0, } },
  { { g.String }, { fg = c.surly_2, italic = true } },
  { { g.Character, g.Boolean, g.Number, g.Float, g.Constant, }, { fg = c.surly_0, } },
  { { g.Keyword, g.Conditional, g.Repeat, g.Label, g.Exception, }, { fg = c.bucky_0 } },
  { { g.Type, g.Typedef, }, { fg = c.sandy_0, } },
  { { g.Variable, }, { fg = c.sally_0, } },
  { { g.Underlined, }, { fg = c.chitter_0, underline = true, } },
  { { g.Todo, }, { fg = c.sally_2, bold = true, italic = true, } },
  { { g.Done, }, { fg = c.hammy_0, bold = true, italic = true, } },
}

return attributes
