local g = require('gruvsquirrel.highlight-groups.standard')
local mapper = require('gruvsquirrel.util.mapper')

local M = {
  attributes = function()
    local d = require('gruvsquirrel.common.highlight_aliases').get()
    return mapper.highlight_group_mapper({
      { { g.ColorColumn }, d.bg_dark0 },
      { { g.LineNr, g.LineNrAbove, g.LineNrBelow }, d.fg_gray3 },
      { { g.CursorLine }, d.__bg_dark1_ctermfg_hack },
      { { g.CursorColumn }, d.bg_dark5 },
      { { g.Visual, g.VisualNOS }, d.bg_dark3 },
      { { g.Statement, g.Conceal, g.Identifier, g.Field, g.Property }, d.fg_blue0 },
      { { g.Directory }, d.fg_blue0_bold },
      { { g.CurSearch, g.IncSearch }, d.fg_dark0_bg_yellow0 },
      { { g.Cursor, g.lCursor, g.TermCursor }, d._reverse },
      { { g.DiffAdd, g.DiffChange }, d.bg_green1 },
      { { g.DiffDelete }, d.fg_dark0_bg_purple4 },
      { { g.DiffText }, d.fg_green2_reverse },
      { { g.NonText, g.Whitespace }, d.fg_gray1 },
      { { g.EndOfBuffer }, d.fg_dark1_bg_dark0 },
      { { g.TermCursorNC }, d._none },
      { { g.Folded }, d.fg_gray0_bg_dark0_italic },
      { { g.FoldColumn, g.CursorLineFold }, d.fg_gray0_bg_dark0 },
      { { g.Substitute, g.Search }, d.fg_dark0_bg_green7 },
      { { g.CursorLineNr }, d.fg_yellow0_bg_dark1 },
      { { g.MatchParen, g.MatchParenCur }, d.fg_gray0_italic },
      { { g.ModeMsg, g.MoreMsg, g.Question }, d.fg_yellow0_bold },
      { { g.MsgArea }, d.fg_light0_bg_dark5 },
      { { g.MsgSeparator }, d.fg_dark5_bg_dark6 },
      { { g.Normal, g.NormalNC }, d.fg_light0_bg_dark0 },
      { { g.NormalFloat, g.Pmenu }, d.fg_light0_bg_dark6 },
      { { g.FloatBorder }, d.fg_gray1_bg_dark6 },
      { { g.FloatShadow }, d.bg_dark5 },
      { { g.FloatShadowThrough }, d.bg_dark5_blend100 },
      -- { { g.NormalNC },                                                                              d.cola_nut },
      { { g.PmenuSel, g.QuickFixLine, g.WildMenu }, d.bg_blue3 },
      { { g.PmenuSbar, g.TabLineFill }, d.bg_dark6 },
      { { g.PmenuThumb }, d.bg_dark3 },
      { { g.SignColumn, g.CursorLineSign }, d._none },
      { { g.SpecialKey }, d.fg_green0_bg_dark0_bold },
      { { g.SpellBad }, d.sp_red0_undercurl },
      { { g.SpellCap }, d.sp_blue4_undercurl },
      { { g.SpellRare }, d.sp_purple3_undercurl },
      { { g.WinBar, g.TabLine }, d.fg_gray6_bg_dark6_bold },
      { { g.WinBarNC }, d.fg_gray4_bg_dark6 },
      { { g.StatusLine }, d.fg_gray6_bg_dark1 },
      { { g.StatusLineNC }, d.fg_gray6_bg_dark1_italic },
      { { g.TabLineSel }, d.fg_gray4 },
      { { g.Title, g.Function, g.FloatTitle }, d.fg_green0 },
      { { g.FloatTitle }, d.fg_dark6_bg_gray1_bold },
      { { g.WarningMsg }, d.fg_orange0 },
      { { g.Error, g.ErrorMsg }, d.fg_red0_bold },
      { { g.WinSeparator, g.VertSplit }, d.fg_gray1_bg_dark1 },
      { { g.Operator }, d.fg_orange0_italic },
      { { g.Comment }, d.fg_gray0_italic },
      { { g.PreProc, g.Define, g.Macro, g.Include, g.Structure }, d.fg_blue4 },
      {
        { g.Delimiter, g.Debug, g.StorageClass, g.Tag, g.Special, g.SpecialChar, g.SpecialComment },
        d.fg_orange0,
      },
      { { g.String }, d.fg_purple2_italic },
      { { g.Character, g.Boolean, g.Number, g.Float, g.Constant }, d.fg_purple0 },
      { { g.Keyword, g.Conditional, g.Repeat, g.Label, g.Exception }, d.fg_red0 },
      { { g.Type, g.Typedef }, d.fg_yellow0 },
      { { g.Variable }, d.fg_light0 },
      { { g.Underlined }, d.fg_blue0_underline },
      { { g.Todo }, d.fg_light2_bold_italic },
      { { g.Done }, d.fg_orange0_bold_italic },
      {
        {
          g.DiagnosticError,
          g.DiagnosticFloatingError,
          g.DiagnosticVirtualTextError,
          g.DiagnosticSignError,
        },
        d.fg_red0,
      },
      {
        {
          g.DiagnosticHint,
          g.DiagnosticFloatingHint,
          g.DiagnosticVirtualTextHint,
          g.DiagnosticSignHint,
        },
        d.fg_blue4,
      },
      {
        {
          g.DiagnosticInfo,
          g.DiagnosticFloatingInfo,
          g.DiagnosticVirtualTextInfo,
          g.DiagnosticSignInfo,
        },
        d.fg_gray2,
      },
      {
        {
          g.DiagnosticWarn,
          g.DiagnosticFloatingWarn,
          g.DiagnosticVirtualTextWarn,
          g.DiagnosticSignWarn,
        },
        d.fg_yellow0,
      },
      {
        { g.DiagnosticOk, g.DiagnosticFloatingOk, g.DiagnosticVirtualTextOk, g.DiagnosticSignOk },
        d.fg_light0,
      },
      { { g.DiagnosticUnderlineError }, d.sp_red0_underline },
      { { g.DiagnosticUnderlineHint }, d.sp_blue4_underline },
      { { g.DiagnosticUnderlineInfo }, d.sp_blue_underline },
      { { g.DiagnosticUnderlineWarn }, d.sp_yellow0_underline },
      { { g.DiagnosticUnderlineOk }, d.sp_green0_underline },
    })
  end,
}
return M
