-- TODO: check if I want to do this
-- -- neovim terminal mode colors
-- local function set_terminal_colors(colors)
--   vim.g.terminal_color_0 = colors.bg0
--   vim.g.terminal_color_1 = colors.neutral_red
--   vim.g.terminal_color_2 = colors.neutral_green
--   vim.g.terminal_color_3 = colors.neutral_yellow
--   vim.g.terminal_color_4 = colors.neutral_blue
--   vim.g.terminal_color_5 = colors.neutral_purple
--   vim.g.terminal_color_6 = colors.neutral_aqua
--   vim.g.terminal_color_7 = colors.fg4
--   vim.g.terminal_color_8 = colors.gray
--   vim.g.terminal_color_9 = colors.red
--   vim.g.terminal_color_10 = colors.green
--   vim.g.terminal_color_11 = colors.yellow
--   vim.g.terminal_color_12 = colors.blue
--   vim.g.terminal_color_13 = colors.purple
--   vim.g.terminal_color_14 = colors.aqua
--   vim.g.terminal_color_15 = colors.fg1
-- end
return {}
-- curl -s https://gist.githubusercontent.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263/raw/e50a28ec54188d2413518788de6c6367ffcea4f7/print256colours.sh | bash

